### ISSUE TITLE
Dynamic Table/Database name

### ISSUE THREAD

**Issue by mdibaiee** [winterland1989/mysql-haskell#11]
Hi,

Suppose I want to run the query below:

```
"CREATE DATABASE IF NOT EXISTS " ++ database
```

now this is not possible as the `Query` type doesn't allow it, on the other hand, using
`renderParams` and `MySQLText` or `MySQLBytes` puts single quotes around the parameter, which is a syntax error for database/table name. 

What's the correct way to work around this problem?

Thanks in advance.

**Comment by winterland1989** [comment]
If you go down to that level, i would suggest you to directly use `Query` constructor to create queries.

**Comment by mdibaiee** [comment]
@winterland1989 I see, I thought the constructor was not exported, that's why I didn't even consider that option. :grin:

Thanks anyways, the library has proved to be quite useful :+1:

**Comment by winterland1989** [comment]
Happy to know it helps ; )
