### ISSUE TITLE
mysql-haskell disabled on stackage

### ISSUE THREAD

**Issue by cdornan** [winterland1989/mysql-haskell#16]
Hi,

We have suspended mysql-haskell from stackage-nightly because it is incompatible with these packages.

memory-0.14.6 is out of bounds for:
- [ ] mysql-haskell-0.8.1.0 (< =0.14.2). No maintainer. @winterland1989. Used by: library

tcp-streams-1.0.1.0 (Winter Land <winterland1989@gmail.com> @winterland1989) is out of bounds for:
- [ ] mysql-haskell-0.8.1.0 (==0.6.*). No maintainer. @winterland1989. Used by: library

tls-1.4.0 is out of bounds for:
- [ ] mysql-haskell-0.8.1.0 (>=1.3.5 && < 1.4). No maintainer. @winterland1989. Used by: library

Can it be made to work with these packages?

**Comment by winterland1989** [comment]
Sorry for the delay, i will try to bring the dep updated this week.
