### ISSUE TITLE
guide have little bugs 

### ISSUE THREAD

**Issue by icecraft** [winterland1989/mysql-haskell#17]
hello ! 
there is something wrong in the README.md 
`
    ...
    s <- prepareStmt conn "SELECT * FROM some_table where person_age > ?"
    ...
    (defs, is) <- queryStmt s [MySQLInt32U 18]
    ...
`
shoulde be 
`
    ...
    s <- prepareStmt conn "SELECT * FROM some_table where person_age > ?"
    ...
    (defs, is) <- queryStmt  conn s [MySQLInt32U 18]
    ...
`

**Comment by winterland1989** [comment]
Ah, good catch.

**Comment by winterland1989** [comment]
Fixed.
