### ISSUE TITLE
UnconsumedResultSet is thrown when runing a query inside a transaction

### ISSUE THREAD

**Issue by jeffersoncarpenter** [winterland1989/mysql-haskell#19]
This code throws an `UnconsumedResultSet` exception:

```
(defs, rowStreams) <- withTransaction db $ do
  execute_ db foo
  execute_ db bar
  query_ db quux
```

Apparently because the `execute_ conn "COMMIT"` statement at the bottom of `withTransaction` is executed before the result returned by `query_` is consumed.  I'm not sure if this is easy or a good idea, but can that behavior be changed so that the above code will run?

One possible solution is to instead write this:

```
(defs, rows) <- withTransaction db $ do
  execute_ db foo
  execute_ db bar
  (defs, rowStreams) <- query_ db quux
  rows <- toList rowStreams
  return (defs, rows)
```

Which (in my case) does work, but might not if you're relying on the laziness of the returned rows.  Are there any other solutions, namely ones that allow the returned rows to still be lazy?

**Comment by winterland1989** [comment]
This will be quite difficult since MySQL server expects you to consume the result before issuing another command, and i don't think there're other ways to make MySQL cache the result for you. 

Can you give more detail on why you're doing streaming processing inside a transaction? Also read https://dev.mysql.com/doc/refman/5.5/en/innodb-locking-reads.html . `select` is not quite like `readTVar`.

**Comment by jeffersoncarpenter** [comment]
I'm adding a row, and simultaneously retrieving its auto-incremented ID.  I'm doing this via an `insert` statement, followed by the statement `SELECT id FROM [table] ORDER BY id DESC LIMIT 1`, and putting both statements into a transaction so that I don't accidentally insert two elements before retrieving their IDs.

**Comment by winterland1989** [comment]
Ah, then you don't have to do streaming, just consume the one element list and cache it on ghc heap.

**Comment by jeffersoncarpenter** [comment]
Okay, I'm fine with closing this issue.  Somebody else can open one if they need to stream data selected from inside a transaction.

**Comment by winterland1989** [comment]
BTW. I believe you should check the `OK` packet which `execute/execute_` would return upon a successful `INSERT`. It has an `okLastInsertID` field which may suit your need.

**Comment by jeffersoncarpenter** [comment]
Thanks for the tip, I did not know about that.
