### ISSUE TITLE
UnexpectedPacket (Packet {pLen = 1, pSeqN = 1, pBody = "\SOH"})

### ISSUE THREAD

**Issue by sfilargi** [winterland1989/mysql-haskell#22]
I am seeing `UnexpectedPacket`. Is it my fault or the library?

My main looks like this:

```
main :: IO ()
main = do
    putStrLn $ "http://localhost:8080/"
    pool <- getPool
    (g, c) <- connectDetail defaultConnectInfoMB4 
        { ciUser = "root"
        , ciPassword = "secret"
        , ciDatabase = "test"
        , ciHost = "db" }
    execute_ c "SELECT 1"
    run 8080 $ app $ pool
```

    root@dd742a406138:/ws/smtp# stack exec smtp-exe
    http://localhost:8080/
    smtp-exe: UnexpectedPacket (Packet {pLen = 1, pSeqN = 1, pBody = "\SOH"})

To repro:

```
git clone https://gitlab.com/sfilargi/smtp
cd smtp
docker-compose build
docker-compose run web bash
cd stmp
stack exec smtp-exe
```

**Comment by sfilargi** [comment]
> It seems i don't have the permission to view your project on gitlab, nor clone it.

Oops, sorry, I made it public now.

> Prelude Database.MySQL.Base> query_ c "SELECT 1"
> *** Exception: ERRException (ERR {errCode = 1096, errState = "HY000", errMsg = "No tables used"})

> Which is somewhat expected, Do you think this is not the right behavior for this query?

No, what you see is correct. However that's not what I see. I see `UnexpectedPacket (Packet {pLen = 1, pSeqN = 1, pBody = "\SOH"}) `

Probably has to do with the mariadb version?

**Comment by winterland1989** [comment]
@sfilargi , Did you test with `query_ c "SELECT 1"` instead of `execute_ c "SELECT 1"` ?

**Comment by sfilargi** [comment]
Yes. See https://vimeo.com/282068553 skip to 8:22. 


PS: database `test` is already created in my setup.

**Comment by sfilargi** [comment]
Thanks. It was that, sorry.

**Comment by winterland1989** [comment]
No problem ；）
