### ISSUE TITLE
extract fields from MySQLValue

### ISSUE THREAD

**Issue by politrons** [winterland1989/mysql-haskell#24]
Hi, I´m trying to extract the values form the query. I have my Just MySQLValue but looking the code I cannot figure how to extract the values:

`Just (User {userId = 10000, userName = "value"})
`
Here the whole program

```
getUserById :: Int -> IO (Maybe User)
getUserById id = let userId = id in do
            conn <- createConnection
            (columnDef, inputStream) <- query conn selectByIdQuery [One $ MySQLInt32 (intToInt32 userId)]
--            print =<< Streams.read inputStream
            maybeMySQLValue <- Streams.read inputStream
            return (transformToUser <$> maybeMySQLValue)

transformToUser :: [MySQLValue] -> User
transformToUser maybeMySQLValue = User 1 "We need to get the real use data"
```

Regards

**Comment by winterland1989** [comment]
This is something usually done ORMs such as [persistent](http://hackage.haskell.org/package/persistent) combining with an adapter like [persistent-mysql-haskell](http://hackage.haskell.org/package/persistent-mysql-haskell). But you can do it yourself if you don't want to go through template haskell. Let's say your user table has three columns:  user id, user age, and user name, which have `longlong`, `Unsigned tiny` and `varchar`  mysql types respectively. Then following function can be used to convert a row into a User record:

```haskell
data User = User { userId :: Int64 , userName :: Text }

transformToUser :: [MySQLValue] -> User
transformToUser [MySQLInt64 uid, MySQLInt8U _age, MySQLText name] = User uid name 
```

**Comment by politrons** [comment]
Elegant and simple thanks!!!
