### ISSUE TITLE
export MySQLConn constructor

### ISSUE THREAD

**Issue by kuribas** [winterland1989/mysql-haskell#27]
Hi, I am writing a MySQL backend for Selda.  I'd like to be able to bypass the MySQLValue datatype and encode directly to a selda SqlValue datatype, to avoid doing redundant conversions.  Also, the selda backend doesn't distinguish between queries and commands, so I must be able to retrieve the resultset and number of affected rows for both..  
To do those thinkgs i need to be able to use the MySQLConn constructor, which isn't exported.
EDIT: additional question: is it possible to get the OK packet for a query?  I don't see any code that parses the OK packet in the implementation of query_
EDIT2: ok, I figured it out.  If the OK packet is send, it will have 0 as the first byte.  The query code reads is as the number of rows to return, so returns an empty list.  I can detect this, and if the ok packet is found it returns the number of rows, otherwise the result set.  With the current code that isn't possible.
EDIT3: it seems it's possible after all, I just need to define my own connection datatype.  I'll still leave this open in case you have better ideas.

**Comment by winterland1989** [comment]
1. The `MySQLConn` is exposed from `Database.MySQL.Connection` module in case you need to access low-level network streams.

2. Of course it's possible to fetch a `OK` packet, see `waitCommandReply / readPacket` from `MySQL.Connection` module.

3. I'm not sure i understand your third issue, the `Packet` is also exposed so you may use that.

**Comment by kuribas** [comment]
Sorry about my re-edits, for some reason I couldn't see your reply...

   1. That will solve my issue.  I can now write my own query function which will work with selda-backend.  
   2. WaitCommandReply will throw an error when it sees a result reply.  I need to be able to pick the right result value (IO (Int, [[SqlValue]]) based on the type of the packet (Ok packet or result packet).  But I suppose it's simply a result packet if it's not an OK, ERR, or EOF packet, so that also solves this issue.
