### ISSUE TITLE
Database.MySQL.Base connectDetail password Access denied 

### ISSUE THREAD

**Issue by ilyazuev** [winterland1989/mysql-haskell#4]
I am trying to connect with my MySql server via Haskel and using your mysql-haskell library.
When the connection is **with password** then i get the following error:

ERRException (ERR {errCode = 1045, errState = "28000", errMsg = "Access denied for user 'test'@'localhost' (using password: YES)"})

but **without password** it works fine.

Greeting {
greetingProtocol = 10,
greetingVersion = "5.5.13",
greetingConnId = 67,
greetingSalt1 = "]G-IfJzJ",
greetingCaps = 2148530175,
greetingCharset = 8,
greetingStatus = 2,
greetingSalt2 = "CQMm]k%o$a@W\NUL",
greetingAuthPlugin = "mysql_native_password"}

Example: 
(greeting,conn)<-connectDetail defaultConnectInfo{ciUser="test", ciPassword="12345",ciDatabase="phonebook",ciHost="localhost"}

**Comment by winterland1989** [comment]
Can you provide the version of `mysql-haskell`? In MySQL 0.4.x we introcuced this regression, but it should be fixed in 0.5.0.

**Comment by ilyazuev** [comment]
Yes, super, solved!!!!Thank you 31.08.2016, 13:58, "winterland" <notifications@github.com>:Can you provide the version of mysql-haskell? In MySQL 0.4.x we introcuced this regression, but it should be fixed in 0.5.0.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
